baseURL = 'https://panchatantras.com/'
languageCode = 'en-us'
title = 'Panchatantras!'
theme = 'ananke'
# post pagination
paginate = 10 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 20 # see https://gohugo.io/content-management/excerpts/

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"

[params.navigation]
    #other stuff
    logo = "images/logo.png"


[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Technology'
    pageRef = '/tech'
    weight = 20
  [[menus.main]]
    name = 'Comic'
    pageRef = '/comic'
    weight = 30
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40
  