baseURL = 'https://panchatantras.com/'
languageCode = 'en-us'
title = 'Panchatantras!'
theme = 'ananke'
# post pagination
paginate = 10 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 20 # see https://gohugo.io/content-management/excerpts/

#################### default parameters ################################
[params]
  site_logo = "images/logo.png"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-green"
  home = "Home"
  # Meta data
  description = "This is meta description"
  enableRobotsTXT = true
  featured_image = "images/home.jpeg"
  commentoEnable = true
  show_reading_time = true
  recent_posts_number = 5
  date_format = "2. January 2006"

[params.navigation]
    #other stuff
    logo = "images/logo.png"


[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/girishtripurana"

[[params.ananke_socials]]
name = "linkedIn"
url = "https://www.linkedin.com/in/girish-tripurana-1351b231/"

[services.disqus]
  shortname = 'Girish'
